# Generated by Django 4.2.13 on 2024-05-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('lecture_number', models.CharField(max_length=3)),
                ('start_time', models.CharField(choices=[('09:10', '09:10 - 10:00'), ('10:00', '10:00 - 10:50'), ('10:50', '10:50 - 11:40'), ('11:40', '11:40 - 12:30'), ('12:30', '12:30 - 13:30'), ('13:30', '13:30 - 14:20'), ('14:20', '14:20 - 15:10'), ('15:10', '15:10 - 16:00'), ('16:00', '16:00 - 16:50')], max_length=5)),
                ('end_time', models.CharField(choices=[('09:10', '09:10 - 10:00'), ('10:00', '10:00 - 10:50'), ('10:50', '10:50 - 11:40'), ('11:40', '11:40 - 12:30'), ('12:30', '12:30 - 13:30'), ('13:30', '13:30 - 14:20'), ('14:20', '14:20 - 15:10'), ('15:10', '15:10 - 16:00'), ('16:00', '16:00 - 16:50')], max_length=5)),
                ('employee_code', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject')),
            ],
        ),
    ]
