# Generated by Django 4.2.13 on 2024-05-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_employee_email_alter_employee_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('09:30', '09:30 - 10:20'), ('10:20', '10:20 - 11:10'), ('11:10', '11:10 - 12:00'), ('12:00', '12:00 - 12:50'), ('12:50', '12:50 - 02:20'), ('02:20', '02:30 - 03:10'), ('03:10', '03:10 - 04:00'), ('04:00', '04:00 - 05:00')], default='09:30', max_length=5),
        ),
    ]
