# Generated by Django 4.2.13 on 2024-05-15 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_schedule_employee_name_alter_schedule_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='employee_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.employee'),
        ),
    ]
