# Generated by Django 4.2.13 on 2024-05-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_classtime_role_workingdays_alter_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.department')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.role')),
            ],
        ),
    ]
