# Generated by Django 4.2.13 on 2024-05-16 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_sessionalmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sessionalmarks',
            name='sessional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.sessional'),
        ),
    ]
