# Generated by Django 4.2.13 on 2024-05-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_sessional_alter_sessionalmarks_sessional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionalmarks',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.department'),
        ),
        migrations.AddField(
            model_name='sessionalmarks',
            name='sem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.semester'),
        ),
    ]
