# Generated by Django 4.2.13 on 2024-05-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_rename_sessional_sessionalmarks_sessionalno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.workingdays'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.classtime'),
        ),
    ]
