# Generated by Django 4.2.13 on 2024-05-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lecture_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('09:30', '09:30 - 10:20'), ('10:20', '10:20 - 11:10'), ('11:10', '11:10 - 12:00'), ('12:00', '12:00 - 12:50'), ('12:50', '12:50 - 02:20'), ('02:20', '02:20 - 04:00'), ('04:00', '04:00 - 05:00')], default='09:30', max_length=5),
        ),
    ]
