# Generated by Django 4.2.13 on 2024-05-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_subject_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_Type',
            field=models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Practical', 'Practical')], max_length=50, null=True),
        ),
    ]
