# Generated by Django 4.2.13 on 2024-05-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_classtime_role_workingdays_alter_schedule_time'),
        ('student', '0002_alter_student_branch_alter_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.classtime'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='faculty.semester'),
        ),
    ]
