# Generated by Django 4.2.13 on 2024-05-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='erp_id',
            new_name='abc_id',
        ),
    ]
