# Generated by Django 4.2.13 on 2024-05-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0008_student_address_student_adhar_no_student_category_and_more'),
        ('faculty', '0023_subject_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.department')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeMan.feetype')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('dues', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeMan.feetype')),
                ('req_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeMan.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
