# Generated by Django 4.2.13 on 2024-05-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_attendance_class_time_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='class_time',
            new_name='classTime',
        ),
    ]
